# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: pinellolab/crispresso2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            rm -rf /opt/conda/bin/CRISPRess*
            rm -rf /opt/conda/lib/python2.7/site-packages/CRISPResso2*
            python setup.py install

      - save_cache:
          paths:
            - /opt/conda/
          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: test-alive
          command: |
            CRISPResso -h

      - run:
          name: test-crispresso
          command: |
                  CRISPResso -r1 tests/FANC.Cas9.fastq -a CGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCGGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -g GGAATCCCTTCTGCAGCACC --debug > test-reports/test-crispresso.out 2>&1
                  diff CRISPResso_on_FANC.Cas9/Reference.nucleotide_frequency_table.txt tests/expectedResults/CRISPResso_on_FANC.Cas9/Reference.nucleotide_frequency_table.txt >> test-reports/test-crispresso.out 2>&1
                  diff CRISPResso_on_FANC.Cas9/CRISPResso_quantification_of_editing_frequency.txt tests/expectedResults/CRISPResso_on_FANC.Cas9/CRISPResso_quantification_of_editing_frequency.txt >> test-reports/test-crispresso.out 2>&1

      - store_artifacts:
          path: test-reports
          destination: test-reports
