# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: pinellolab/crispresso2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            rm -rf /opt/conda/bin/CRISPRess*
            rm -rf /opt/conda/lib/python2.7/site-packages/CRISPResso2*
            python setup.py install

      - save_cache:
          paths:
            - /opt/conda/
          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: test-alive
          command: |
            CRISPResso -h

      - run:
          name: test-crispresso
          command: |
                  CRISPResso -r1 tests/FANC.Cas9.fastq -a CGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCGGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -g GGAATCCCTTCTGCAGCACC --debug > test-crispresso.out 2>&1
                  diff CRISPResso_on_FANC.Cas9/Nucleotide_frequency_table.txt tests/expectedResults/CRISPResso_on_FANC.Cas9/Nucleotide_frequency_table.txt >> test-crispresso.out 2>&1
                  diff CRISPResso_on_FANC.Cas9/CRISPResso_quantification_of_editing_frequency.txt tests/expectedResults/CRISPResso_on_FANC.Cas9/CRISPResso_quantification_of_editing_frequency.txt >> test-crispresso.out 2>&1

      - run:
          name: test-crispresso-with-params
          command: |
                  CRISPResso -r1 tests/FANC.Cas9.fastq -a CGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCGGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -g GGAATCCCTTCTGCAGCACC -e CGGCCGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCTGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -c GGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTT --dump -qwc 20-30_45-50 -q 30 --default_min_aln_score 80 -an FANC -n params --debug > test-crispresso-with-params.log
                  diff CRISPResso_on_params/FANC.Nucleotide_frequency_table.txt tests/expectedResults/CRISPResso_on_params/FANC.Nucleotide_frequency_table.txt >> test-crispresso-with-params.out 2>&1
                  diff CRISPResso_on_params/CRISPResso_quantification_of_editing_frequency.txt tests/expectedResults/CRISPResso_on_params/CRISPResso_quantification_of_editing_frequency.txt >> test-crispresso-with-params.out 2>&1

      - run:
          name: test-crispresso-batch
          command: |
                  CRISPRessoBatch -bs tests/FANC.batch -a CGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCGGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -g GGAATCCCTTCTGCAGCACC -p 2 --debug --base_editor --debug > test-crispresso-batch.out
                  diff CRISPRessoBatch_on_FANC/MODIFICATION_FREQUENCY_SUMMARY.txt tests/expectedResults/CRISPRessoBatch_on_FANC/MODIFICATION_FREQUENCY_SUMMARY.txt >> test-crispresso-batch.out 2>&1

      - run:
          name: test-crispresso-pooled
          command: |
                  CRISPRessoPooled -r1 tests/Both.Cas9.fastq -f tests/Cas9.amplicons.txt -p 2 --keep_intermediate --min_reads_to_use_region 100 --debug > test-crispresso-pooled.out
                  diff CRISPRessoPooled_on_Both.Cas9/SAMPLES_QUANTIFICATION_SUMMARY.txt tests/expectedResults/CRISPRessoPooled_on_Both.Cas9/SAMPLES_QUANTIFICATION_SUMMARY.txt >> test-crispresso-pooled.out 2>&1

      - run:
          name: test-crispresso-wgs
          command: |
                  CRISPRessoWGS -b tests/Both.Cas9.fastq.smallGenome.bam -r tests/smallGenome/smallGenome.fa -f tests/Cas9.regions.txt --debug > test-crispresso-wgs.out 2>&1
                  diff CRISPRessoWGS_on_Both.Cas9.fastq.smallGenome/SAMPLES_QUANTIFICATION_SUMMARY.txt tests/expectedResults/CRISPRessoWGS_on_Both.Cas9.fastq.smallGenome/SAMPLES_QUANTIFICATION_SUMMARY.txt >> test-crispresso-wgs.out 2>&1
      - run:
          name: test-crispresso-compare
          command: |
                  CRISPRessoCompare CRISPRessoBatch_on_FANC/CRISPResso_on_Cas9/ CRISPRessoBatch_on_FANC/CRISPResso_on_Untreated/ --debug > test-crispresso-compare.out 2>&1

      - store_artifacts:
          path: test-crispresso.out
      - store_artifacts:
          path: test-crispresso-with-params.out
      - store_artifacts:
          path: test-crispresso-batch.out
      - store_artifacts:
          path: test-crispresso-pooled.out
      - store_artifacts:
          path: test-crispresso-wgs.out
      - store_artifacts:
          path: test-crispresso-compare.out
