name: Run Pytest on Push

on:
  push:
    paths:
      - '.github/workflows/pytest.yml'
      - '.github/envs/test_env.yml'
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: test_env
          environment-file: .github/envs/test_env.yml

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ bowtie2 samtools libsys-hostname-long-perl
    
    - name: Install dependencies
      run: |
        conda create -n test_env -c defaults -c conda-forge -c bioconda -y --debug -c bioconda pip trimmomatic flash numpy cython jinja2 tbb=2020.2 pyparsing=2.3.1 scipy matplotlib pandas plotly
        conda init
        
    - name: Install Pytest
      run: |
        pip install pytest pytest-cov
    
    - name: Install CRISPResso
      run: |
        pip install .

    - name: Run Pytest
      run: | 
        pytest --cov CRISPResso2/CRISPResso2
